import type { IItem } from "@/api/items.types";
import { PopupTypes } from "@/api/items.types";

const items: IItem[] = [
  {
    id: 1,
    icon: "/src/assets/icons/calendar/15.svg",
    isActive: true,
    popup: {
      id: 1,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 2,
    icon: "/src/assets/icons/calendar/16.svg",
    isActive: true,
    popup: {
      id: 2,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 3,
    icon: "/src/assets/icons/calendar/17.svg",
    isActive: true,
    popup: {
      id: 3,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 4,
    icon: "/src/assets/icons/calendar/18.svg",
    isActive: true,
    popup: {
      id: 4,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 5,
    icon: "/src/assets/icons/calendar/19.svg",
    isActive: true,
    popup: {
      id: 5,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 6,
    icon: "/src/assets/icons/calendar/20.svg",
    isActive: true,
    popup: {
      id: 6,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 7,
    icon: "/src/assets/icons/calendar/21.svg",
    isActive: true,
    popup: {
      id: 3,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 8,
    icon: "/src/assets/icons/calendar/22.svg",
    isActive: true,
    popup: {
      id: 8,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 9,
    icon: "/src/assets/icons/calendar/23.svg",
    isActive: true,
    popup: {
      id: 9,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 10,
    icon: "/src/assets/icons/calendar/24.svg",
    isActive: true,
    popup: {
      id: 10,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 11,
    icon: "/src/assets/icons/calendar/25.svg",
    isActive: true,
    popup: {
      id: 11,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 12,
    icon: "/src/assets/icons/calendar/26.svg",
    isActive: true,
    popup: {
      id: 12,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 13,
    icon: "/src/assets/icons/calendar/27.svg",
    isActive: true,
    popup: {
      id: 13,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 14,
    icon: "/src/assets/icons/calendar/28.svg",
    isActive: true,
    popup: {
      id: 14,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 15,
    icon: "/src/assets/icons/calendar/29.svg",
    isActive: true,
    popup: {
      id: 15,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 16,
    icon: "/src/assets/icons/calendar/30.svg",
    isActive: true,
    popup: {
      id: 16,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 17,
    icon: "/src/assets/icons/calendar/31.svg",
    isActive: true,
    popup: {
      id: 17,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 18,
    icon: "/src/assets/icons/calendar/1.svg",
    isActive: true,
    popup: {
      id: 18,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 19,
    icon: "/src/assets/icons/calendar/2.svg",
    isActive: true,
    popup: {
      id: 19,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 20,
    icon: "/src/assets/icons/calendar/3.svg",
    isActive: true,
    popup: {
      id: 20,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 21,
    icon: "/src/assets/icons/calendar/4.svg",
    isActive: true,
    popup: {
      id: 21,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 22,
    icon: "/src/assets/icons/calendar/5.svg",
    isActive: true,
    popup: {
      id: 22,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 23,
    icon: "/src/assets/icons/calendar/6.svg",
    isActive: true,
    popup: {
      id: 23,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
  {
    id: 24,
    icon: "/src/assets/icons/calendar/7.svg",
    isActive: true,
    popup: {
      id: 24,
      type: PopupTypes.Story,
      title: "Проект «Дистанционное образование»",
      image: "https://via.placeholder.com/548x240",
      text: "<p>Проект «Дистанционное образование» стартовал в 2013 году. Изначально у него была задача помочь подросткам из детских домов и интернатов подготовиться к поступлению в колледжи и вузы. Когда проект заработал, стало ясно, что работать нужно не только в этом направлении, что детям нужна другая помощь.</p> <p>В 2021-2022 учебном году мы приняли в проект 238 подростков из 32 учреждений. Наши ученики живут в разных точках: Москве, Санкт-Петербурге, Московской, Нижегородской, Астраханской, Владимирской, Челябинской, Ивановской, Саратовской, Тульской, Костромской, Мурманской и Ростовской области, в Удмуртии, Карелии, Татарстане, Красноярском крае и даже в Аргентине.</p>",
      supportLink: "https://www.google.ru/",
      aboutLink:
        "https://otkazniki.ru/events/news/my-ne-provodim-otbor-motivirovannykh-podrostkov-my-pomogaem-vsem-kto-khochet-poprobovat-uchitsya/",
    },
  },
  {
    id: 25,
    icon: "/src/assets/icons/calendar/8.svg",
    isActive: false,
    popup: {
      id: 25,
      type: PopupTypes.Promo,
      title: "Вам подарок от ЛитРес!",
      gift: "Книга из подборки и скидка 20% на каталог",
      code: "ADVENT20",
      link: "https://www.google.ru/",
    },
  },
];

export default items;
